name: ConnectToYT
main: matthbo.plugin.connecttoyt.ConnectToYT
version: 1.0
commands:
    youtube:
        description: Adds a message in the Stefan Help List
        usage: /<command> [player] | /<command> set [url]
