name: ConnectToSocial
main: matthbo.plugin.connecttosocial.ConnectToSocial
version: 1.5
commands:
    social:
        description: View someones SocialMedia via URLs
        usage: /<command> [player] | /<command> set [media] [url] | /<command> reset
